baseURL = 'https://richardgibbon.org/'
languageCode = 'en-us'
title = 'Richard Gibbon'
uglyURLs = "true"
relativeURLs = "true"
[module]
  [[module.imports]]
    path = "github.com/nicokaiser/hugo-theme-gallery/v4"
